// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1R40bEo8sk7SSa3iiTtkfypHX1dTFYNA',
    appId: '1:1098721685102:web:45b6c19dd0c5a33e6ec07f',
    messagingSenderId: '1098721685102',
    projectId: 'awaj-94f35',
    authDomain: 'awaj-94f35.firebaseapp.com',
    storageBucket: 'awaj-94f35.firebasestorage.app',
    measurementId: 'G-83NBRZGJ2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDia-DVQTOYzsVplF21CLp1JkeESPaYJao',
    appId: '1:1098721685102:android:94d7e6686b75e8226ec07f',
    messagingSenderId: '1098721685102',
    projectId: 'awaj-94f35',
    storageBucket: 'awaj-94f35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB52ZODCZzvgjOP8VafCgCyNDaGG-3Rarc',
    appId: '1:1098721685102:ios:b4583400bdfb76df6ec07f',
    messagingSenderId: '1098721685102',
    projectId: 'awaj-94f35',
    storageBucket: 'awaj-94f35.firebasestorage.app',
    iosBundleId: 'com.example.awaj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1R40bEo8sk7SSa3iiTtkfypHX1dTFYNA',
    appId: '1:1098721685102:web:57de9ea3e29679d26ec07f',
    messagingSenderId: '1098721685102',
    projectId: 'awaj-94f35',
    authDomain: 'awaj-94f35.firebaseapp.com',
    storageBucket: 'awaj-94f35.firebasestorage.app',
    measurementId: 'G-R3HQRBHTNJ',
  );
}
